name: Build khristmas

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: khristmas
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libsdl1.2-dev libsdl-image1.2-dev libmikmod-dev
      - name: Build
        run: make
