/*
 * Intro Data Importer (c) 2004 Gautier Portet
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
 */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "SDL.h"


int main (int argc, char *argv[])
{
	char msg[1024];
	FILE *f;
	FILE *m;
	unsigned char *buffer;
	int lenght;
	int i;
	char **p;

	if (argc < 3) {
		puts("bin2c destination source name");
	}

	f = fopen(argv[1], "w");
	fprintf(f,	"/* Generated by Intro-Tools */\n");
	m = fopen(argv[2], "rb");

	fseek(m, 0, SEEK_END);
	lenght = ftell(m);
	buffer = (unsigned char*) malloc(lenght);

	fseek(m, 0, SEEK_SET);
	printf("converting %s (%d bytes)\n", argv[2], lenght);

	fread(buffer, 1, lenght, m);

	fprintf(f, "unsigned char %s[%d]= {\n", argv[3], lenght);

	fprintf(f, "%d", buffer[0]);
	for (i = 1; i < lenght; i++) {
		fprintf(f, ",%d", buffer[i]);
		if ((i&15) == 0)
			fprintf(f, "\n");
	}

	free(buffer);

	fprintf(f, "};\n");
	fclose(f);
	fclose(m);

	return 0;
}
